import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Providers } from "@/store/providers";
import Modal from "@/components/modal/modal";

export const metadata: Metadata = {
  title: "Socca Austria",
  // description: "Generated by create next app",
  openGraph: {
    type: "website",
    title: "Socca Austria",
    siteName: "Socca Austria",
    url: "https://soccaaustria.at/",
    description:
      "Erleben Sie die Spannung unserer neu gegründeten Fußballliga, wo Leidenschaft auf Professionalität trifft.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <>
            <Modal />
            {children}
          </>
        </Providers>
      </body>
    </html>
  );
}
