import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Providers } from "@/store/providers";
import Modal from "@/components/modal/modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pro League",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <>
            <Modal />
            {children}
          </>
        </Providers>
      </body>
    </html>
  );
}
